name: Update Documentation

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2.3.1

      - name: Setup ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1
        id: setup-ffmpeg
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
        
      - name: Install dependencies üîß
        run: |
          python --version
          python -m pip install --upgrade pip
          pip install --quiet pdoc3 tensorflow torch jax jaxlib plotly "nbformat==5.4.0" ipython notebook ipywidgets
          pip install .
          pip list
        
      - name: Build API with pdoc3
        run: pdoc --html --output-dir docs --force phi
        
      - name: Build static HTML for Jupyter Notebooks
        run: |
          jupyter nbconvert --to html --execute --allow-errors docs/*.ipynb
          jupyter nbconvert --to html --output-dir docs/ docs/prerendered/*.ipynb

      - name: Deploy üöÄ
        uses: JamesIves/github-pages-deploy-action@4.1.4  # See https://github.com/marketplace/actions/deploy-to-github-pages
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
